# -*- coding: utf-8 -*-
"""Highlighted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wH9zD_buu8QfieBA-sz8G-gb16t9QKA
"""

# Installing Library
!pip install pymupdf

# ------------------ Import Libraries ------------------
import fitz
import os, json, re
from datetime import datetime
from google.colab import files
from IPython.display import HTML, display

# ------------------ Config ------------------
CONFIG_JSON = {
    "upload_directory": "uploads",
    # Combined ICD-10 and ICD-9 pattern, captures only the codes
    "icd_pattern": r"(?:ICD-(?:10|9)-CM):?\s*\[?([A-Z\d]\d{1,2}(?:\.\d+)?(?:,\s*[\s]*[A-Z\d]\d{1,2}(?:\.\d+)?)*)\]?"
}

UPLOAD_DIR = CONFIG_JSON["upload_directory"]
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs("logs", exist_ok=True)

# ------------------ Logging ------------------
def log(msg):
    logfile = "logs/app.log"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(logfile, "a") as f:
        f.write(f"[{timestamp}] {msg}\n")

# ------------------ Upload PDF ------------------
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]
log(f"Uploaded PDF: {pdf_path}")

# ------------------ Extract + Highlight ------------------
def extract_and_highlight(pdf_path, config):
    doc = fitz.open(pdf_path)
    pdf_data = []

    for page_num, page in enumerate(doc):
        text = page.get_text("text")
        words_data = []
        extracted_icd_codes = []   # <---- NEW

        # ---- ICD Highlight (combined 9 & 10) ----
        for match in re.finditer(config["icd_pattern"], text, re.IGNORECASE):

            codes_str = match.group(1)
            codes = [c.strip() for c in codes_str.split(",")]

            # store ICD codes separately
            extracted_icd_codes.extend(codes)   # <---- NEW

            for code in codes:
                # Search for the code itself, without ICD-xx label
                for inst in page.search_for(code):
                    annot = page.add_highlight_annot(inst)

                    # Color code: red for ICD-10, blue for ICD-9
                    if match.group(0).upper().startswith("ICD-10"):
                        annot.set_colors(stroke=(1, 0.8, 0.8))  # light red
                    else:
                        annot.set_colors(stroke=(0.6, 0.8, 1))  # light blue

                    annot.update()

        # ---- Extract words + coordinates ----
        for w in page.get_text("words"):
            words_data.append({
                "text": w[4],
                "x0": round(w[0], 2),
                "y0": round(w[1], 2),
                "x1": round(w[2], 2),
                "y1": round(w[3], 2)
            })

        # ---- JSON per page ----
        pdf_data.append({
            "page_number": page_num + 1,
            "text_sample": text[:150],
            "extracted_icd_codes": extracted_icd_codes,   # <---- NEW
            "words": words_data
        })

    # ---- Save PDF + JSON ----
    base_name = pdf_path.rsplit(".", 1)[0]
    highlighted_pdf = f"{base_name} 1_highlighted.pdf"
    json_file = f"{base_name} 1_json_words.json"
    doc.save(highlighted_pdf)
    doc.close()

    with open(json_file, "w") as f:
        json.dump(pdf_data, f, indent=4)

    log(f"Highlighted PDF saved: {highlighted_pdf}")
    log(f"Word coordinates JSON saved: {json_file}")

    return highlighted_pdf, json_file

# ------------------ Run extraction & highlight ------------------
highlighted_pdf, json_file = extract_and_highlight(pdf_path, CONFIG_JSON)

# ------------------ Manual download buttons ------------------
def create_download_button(file_path, button_text="Download File"):
    import base64
    with open(file_path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    href = f'<a download="{os.path.basename(file_path)}" href="data:application/octet-stream;base64,{b64}" target="_blank"><button>{button_text}</button></a>'
    display(HTML(href))

# Display download buttons
create_download_button(highlighted_pdf, "Download Highlighted PDF")
create_download_button(json_file, "Download JSON Words Data")

print("✅ Highlighted PDF and JSON ready for download!")

