# -*- coding: utf-8 -*-
"""Highlighted.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19wH9zD_buu8QfieBA-sz8G-gb16t9QKA
"""

# Installing Library
!pip install pymupdf

# ------------------ Importing Libraries ------------------
import fitz
import os, json, re
from datetime import datetime
from google.colab import files
from IPython.display import HTML

# ------------------ Config ------------------
CONFIG_JSON = {
    "upload_directory": "uploads",
    "icd_pattern_10": r"ICD-10-CM:?\s*\[?([A-Z]\d{1,2}(?:\.\d+)?(?:,\s*[\r\n]*[A-Z]\d{1,2}(?:\.\d+)?)*)\]?",
    "icd_pattern_9": r"ICD-9-CM:?\s*([A-Z\d]?\d{1,2}(?:\.\d+)?(?:,\s*[\s]*[A-Z\d]?\d{1,2}(?:\.\d+)?)*)"
}

UPLOAD_DIR = CONFIG_JSON["upload_directory"]
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs("logs", exist_ok=True)

# ------------------ Logging ------------------
def log(msg):
    logfile = "logs/app.log"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(logfile, "a") as f:
        f.write(f"[{timestamp}] {msg}\n")

# ------------------ Upload PDF ------------------
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]
log(f"Uploaded PDF: {pdf_path}")

# ------------------ Extract + Highlight ------------------
def extract_and_highlight(pdf_path, config):
    doc = fitz.open(pdf_path)
    pdf_data = []

    for page_num, page in enumerate(doc):
        text = page.get_text("text")
        words_data = []

        # ---- ICD-10 Highlight ----
        for match in re.finditer(config["icd_pattern_10"], text, re.IGNORECASE):
            label = "ICD-10-CM"
            codes_str = match.group(1)
            codes = [c.strip() for c in codes_str.split(",")]
            for code in codes:
                full_text = f"{label}: {code}"
                for inst in page.search_for(full_text):
                    annot = page.add_highlight_annot(inst)
                    annot.set_colors(stroke=(1, 0.8, 0.8))  # light red
                    annot.update()

        # ---- ICD-9 Highlight ----
        for match in re.finditer(config["icd_pattern_9"], text, re.IGNORECASE):
            label = "ICD-9-CM"
            codes_str = match.group(1)
            codes = [c.strip() for c in codes_str.split(",")]
            for code in codes:
                full_text = f"{label}: {code}"
                for inst in page.search_for(full_text):
                    annot = page.add_highlight_annot(inst)
                    annot.set_colors(stroke=(0.6, 0.8, 1))  # light blue
                    annot.update()

        # ---- Extract words + coordinates ----
        for w in page.get_text("words"):
            words_data.append({
                "text": w[4],
                "x0": round(w[0], 2),
                "y0": round(w[1], 2),
                "x1": round(w[2], 2),
                "y1": round(w[3], 2)
            })

        pdf_data.append({
            "page_number": page_num + 1,
            "text_sample": text[:150],
            "words": words_data
        })

    # ---- Save PDF + JSON ----
    base_name = pdf_path.rsplit(".", 1)[0]
    highlighted_pdf = f"{base_name}_highlighted.pdf"
    json_file = f"{base_name}_words.json"
    doc.save(highlighted_pdf)
    doc.close()

    with open(json_file, "w") as f:
        json.dump(pdf_data, f, indent=4)

    log(f"Highlighted PDF saved: {highlighted_pdf}")
    log(f"Word coordinates JSON saved: {json_file}")

    return highlighted_pdf, json_file

# ------------------ Run extraction & highlight ------------------
highlighted_pdf, json_file = extract_and_highlight(pdf_path, CONFIG_JSON)

# ------------------ Automatic download ------------------
files.download(highlighted_pdf)
files.download(json_file)
print("✅ Highlighted PDF and JSON ready for download!")

# ------------------ Manual download button ------------------
def create_download_button(file_path, button_text="Download Highlighted PDF"):
    import base64
    with open(file_path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    href = f'<a download="{os.path.basename(file_path)}" href="data:application/pdf;base64,{b64}" target="_blank"><button>{button_text}</button></a>'
    return HTML(href)

create_download_button(highlighted_pdf)

